#!/bin/bash

: '
TimeTP

Created by Kyuri Jo on 2016-01-24.
Copyright (c) 2016 Kyuri Jo. All rights reserved.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

----------------------------------------------------------------------
'
echo "TimeTP ver 1.0"

CONF_FILE="$1"

# Read config file and assign values
while read line; do
   echo "$line"
   var=`echo "$line" | awk -F"\t" '{print $1}'`
   param=`echo "$line" | awk -F"\t" '{print $2}'`
   eval $var=$param
done < $CONF_FILE

echo "1. Running Rscript for DEG detection"
python runR.py $CONF_FILE 0;
if [ "$type" == "RNA-seq" ]; then
echo ".. Deseq2 for RNA-seq dataset"
Rscript dataset/$dataDir/deseq2.R
else
echo ".. Limma for microarray dataset"
Rscript dataset/$dataDir/limma.R
fi
python runR.py $CONF_FILE 1;

echo "2. Running TimeTP"
python TimeTP.py $CONF_FILE

